"""

Revenue Forecast page for the CFO Financial Dashboard.

This page shows revenue forecasts generated by the Prophet model.
It displays future revenue predictions, confidence intervals, forecast KPIs, month-by-month forecast details, and model performance metadata.
"""

import os
import sys

import pandas as pd
import plotly.graph_objects as go
import streamlit as st


# ---------------------------------------------------------------------------
# Streamlit page configuration
# ---------------------------------------------------------------------------


st.set_page_config(
    page_title="Revenue Forecast - CFO Dashboard",
    page_icon="chart_with_upwards_trend",
    layout="wide"
)


# ---------------------------------------------------------------------------
# Python import paths
# ---------------------------------------------------------------------------


current_file = os.path.abspath(__file__)
pages_dir = os.path.dirname(current_file)
streamlit_dir = os.path.dirname(pages_dir)
project_root = os.path.dirname(streamlit_dir)

sys.path.insert(0, streamlit_dir)
sys.path.insert(0, project_root)


# ---------------------------------------------------------------------------
# Import reusable helper functions
# ---------------------------------------------------------------------------
# get_monthly_summary() loads historical revenue data from PostgreSQL.
# format_currency() formats numbers like 1250000 into $1.3M.
# ---------------------------------------------------------------------------

from utils.db_queries import get_monthly_summary
from utils.formatters import format_currency


# ---------------------------------------------------------------------------
# Load custom CSS
# ---------------------------------------------------------------------------

css_path = os.path.join(streamlit_dir, "assets", "style.css")

if os.path.exists(css_path):
    with open(css_path, "r", encoding="utf-8") as css_file:
        st.markdown(
            f"<style>{css_file.read()}</style>",
            unsafe_allow_html=True
        )


# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------

st.markdown(
    '<div class="page-header">Revenue Forecast - Prophet ML Model</div>',
    unsafe_allow_html=True
)


# ---------------------------------------------------------------------------
# Sidebar forecast settings
# ---------------------------------------------------------------------------
# The user can control:
# - how many months to forecast
# - whether to show confidence intervals
# - which Prophet model to use
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("### Forecast Settings")

    forecast_periods = st.slider(
        "Forecast months ahead",
        min_value=3,
        max_value=12,
        value=6,
        step=1
    )

    show_confidence = st.checkbox(
        "Show confidence intervals",
        value=True
    )

    selected_department = st.selectbox(
        "Department model",
        ["Company Total", "Sales"],
        index=0
    )


# ---------------------------------------------------------------------------
# Page title
# ---------------------------------------------------------------------------

st.subheader(f"Revenue Forecast - Next {forecast_periods} Months")


# ---------------------------------------------------------------------------
# Load Prophet forecast
# ---------------------------------------------------------------------------
# This section imports the trained Prophet prediction functions.
#
# forecast_department():
# Returns historical fitted values and future forecast values.
#
# get_model_metadata():
# Returns model evaluation information such as MAPE, MAE, and training date.
# ---------------------------------------------------------------------------

with st.spinner("Loading Prophet forecast model..."):
    try:
        from ml.forecasting.predict import forecast_department, get_model_metadata

        # Map the user-friendly dropdown label to the actual saved model key.
        department_model_map = {
            "Company Total": "Company_Total",
            "Sales": "Sales"
        }

        model_key = department_model_map[selected_department]

        forecast_df = forecast_department(
            model_key,
            periods=forecast_periods
        )


        # -------------------------------------------------------------------
        # Validate forecast output
        # -------------------------------------------------------------------
        # The forecast output should contain:
        # - ds
        # - yhat
        # - yhat_lower
        # - yhat_upper
        # - is_forecast
        # -------------------------------------------------------------------

        if forecast_df.empty:
            st.warning("The forecast model returned no data.")
            st.stop()

        required_columns = {
            "ds",
            "yhat",
            "yhat_lower",
            "yhat_upper",
            "is_forecast"
        }

        missing_columns = required_columns - set(forecast_df.columns)

        if missing_columns:
            st.error(
                f"Forecast output is missing required columns: {missing_columns}"
            )
            st.stop()


        # -------------------------------------------------------------------
        # Split forecast output into historical and future data
        # -------------------------------------------------------------------
        # historical:
        # Values fitted by Prophet on past data.
        #
        # future:
        # Actual future predictions.
        # -------------------------------------------------------------------

        historical = forecast_df[~forecast_df["is_forecast"]].copy()
        future = forecast_df[forecast_df["is_forecast"]].copy()

        if future.empty:
            st.warning("No future forecast rows were returned.")
            st.stop()


        # -------------------------------------------------------------------
        # Load actual historical revenue from PostgreSQL
        # -------------------------------------------------------------------
        # We overlay actual revenue on the forecast chart so the user can compare
        # historical performance with future predictions.
        # -------------------------------------------------------------------

        df_summary = get_monthly_summary()

        if df_summary.empty:
            st.warning("No historical revenue data is available.")
            st.stop()


        # -------------------------------------------------------------------
        # Filter actual revenue based on selected model
        # -------------------------------------------------------------------
        # If Company Total is selected, use all departments.
        # If Sales is selected, compare the Sales forecast to Sales actuals.
        # -------------------------------------------------------------------

        if model_key == "Sales":
            actual_source = df_summary[df_summary["department"] == "Sales"].copy()
        else:
            actual_source = df_summary.copy()


        actual_monthly = (
            actual_source
            .groupby(["year", "month"], as_index=False)["total_revenue"]
            .sum()
        )

        actual_monthly["ds"] = pd.to_datetime(
            actual_monthly["year"].astype(str)
            + "-"
            + actual_monthly["month"].astype(str).str.zfill(2)
            + "-01"
        )

        actual_monthly = actual_monthly.sort_values("ds")


        # -------------------------------------------------------------------
        # Forecast KPI cards
        # -------------------------------------------------------------------
        # These KPIs summarize the forecast period.
        # -------------------------------------------------------------------

        average_forecast = future["yhat"].mean()
        peak_forecast = future["yhat"].max()
        total_forecast = future["yhat"].sum()

        average_uncertainty_range = (
            future["yhat_upper"] - future["yhat_lower"]
        ).mean()

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric(
                label="Avg Monthly Forecast",
                value=format_currency(average_forecast)
            )

        with col2:
            st.metric(
                label="Peak Month Forecast",
                value=format_currency(peak_forecast)
            )

        with col3:
            st.metric(
                label=f"Total {forecast_periods}-Month Forecast",
                value=format_currency(total_forecast)
            )

        with col4:
            st.metric(
                label="Avg Uncertainty Range",
                value=format_currency(average_uncertainty_range)
            )

        st.divider()


        # -------------------------------------------------------------------
        # Main forecast chart
        # -------------------------------------------------------------------
        # The chart includes:
        # - actual historical revenue
        # - future forecast line
        # - optional confidence interval
        # - vertical line showing where the forecast starts
        # -------------------------------------------------------------------

        fig = go.Figure()

        # Actual historical revenue line.
        fig.add_trace(
            go.Scatter(
                x=actual_monthly["ds"],
                y=actual_monthly["total_revenue"],
                name="Actual Revenue",
                line=dict(color="#1B3A6B", width=2),
                mode="lines"
            )
        )

        # Optional confidence interval for future forecast.
        if show_confidence:
            fig.add_trace(
                go.Scatter(
                    x=pd.concat([future["ds"], future["ds"][::-1]]),
                    y=pd.concat([
                        future["yhat_upper"],
                        future["yhat_lower"][::-1]
                    ]),
                    fill="toself",
                    fillcolor="rgba(46, 117, 182, 0.15)",
                    line=dict(color="rgba(255,255,255,0)"),
                    name="Confidence Interval",
                    showlegend=True
                )
            )

        # Forecast line.
        fig.add_trace(
            go.Scatter(
                x=future["ds"],
                y=future["yhat"],
                name="Forecast",
                line=dict(color="#E67E22", width=2.5, dash="dash"),
                mode="lines+markers",
                marker=dict(size=7, color="#E67E22")
            )
        )

        # Vertical line separating historical data from forecast data.
        last_actual_date = actual_monthly["ds"].max()

        fig.add_vline(
    x=last_actual_date,
    line_dash="dot",
    line_color="#7F8C8D"
)
        fig.add_annotation(
    x=last_actual_date,
    y=1,
    xref="x",
    yref="paper",
    text="Forecast start",
    showarrow=False,
    xanchor="left",
    yanchor="bottom",
    font=dict(size=11, color="#7F8C8D")
)

        fig.update_layout(
            height=380,
            margin=dict(l=0, r=0, t=20, b=0),
            xaxis_title="",
            yaxis=dict(tickformat="$~s", title=""),
            legend=dict(orientation="h", y=1.12),
            plot_bgcolor="white",
            paper_bgcolor="white",
            hovermode="x unified"
        )

        st.plotly_chart(fig, use_container_width=True)


        # -------------------------------------------------------------------
        # Forecast detail table
        # -------------------------------------------------------------------
        # This table shows each future month with:
        # - forecast value
        # - lower bound
        # - upper bound
        # -------------------------------------------------------------------

        st.subheader("Forecast Detail - Month by Month")

        forecast_table = future[
            ["ds", "yhat", "yhat_lower", "yhat_upper"]
        ].copy()

        forecast_table.columns = [
            "Month",
            "Forecast",
            "Lower Bound",
            "Upper Bound"
        ]

        forecast_table["Month"] = forecast_table["Month"].dt.strftime("%B %Y")

        forecast_table["Forecast"] = forecast_table["Forecast"].apply(
            format_currency
        )

        forecast_table["Lower Bound"] = forecast_table["Lower Bound"].apply(
            format_currency
        )

        forecast_table["Upper Bound"] = forecast_table["Upper Bound"].apply(
            format_currency
        )

        st.dataframe(
            forecast_table,
            use_container_width=True,
            hide_index=True,
            height=250
        )


        # -------------------------------------------------------------------
        # Model metadata
        # -------------------------------------------------------------------
        # This section explains how good the model is.
        #
        # MAPE:
        # Mean Absolute Percentage Error.
        # Lower is better.
        #
        # MAE:
        # Mean Absolute Error.
        # Shows average dollar error.
        # -------------------------------------------------------------------

        st.divider()
        st.subheader("Model Information")

        metadata_df = get_model_metadata()

        if metadata_df.empty:
            st.info("No model metadata is available.")
        else:
            model_row = metadata_df[metadata_df["department"] == model_key]

            if model_row.empty:
                st.info("No metadata found for this model.")
            else:
                row = model_row.iloc[0]

                col1, col2, col3, col4 = st.columns(4)

                with col1:
                    st.metric(
                        label="Model",
                        value="Prophet"
                    )

                with col2:
                    st.metric(
                        label="MAPE",
                        value=f"{row['mape']:.2f}%"
                    )

                with col3:
                    st.metric(
                        label="MAE",
                        value=format_currency(row["mae"])
                    )

                with col4:
                    trained_date = str(row["trained_at"])[:10]

                    st.metric(
                        label="Last Trained",
                        value=trained_date
                    )

                model_quality = (
                    "Good"
                    if row["mape"] < 10
                    else "Review"
                )

                st.info(
                    f"Model quality: {model_quality}. "
                    f"MAPE of {row['mape']:.1f}% means the model's monthly "
                    f"revenue predictions are off by about {row['mape']:.1f}% "
                    f"on average. The model was trained on historical monthly "
                    f"revenue data from 2023 to 2025."
                )


    except FileNotFoundError:
        st.error(
            "Prophet model not found. "
            "Run `python ml/forecasting/train_prophet.py` first."
        )

    except Exception as error:
        st.error(f"Forecast error: {error}")
        st.exception(error)