# Purpose:
# This file manages the PostgreSQL database connection and defines the database
# tables used in the CFO Financial KPI Dashboard project.
#
# I am using SQLAlchemy ORM because it lets me define database tables as Python
# classes instead of writing all CREATE TABLE statements manually.
#
# Database design:
# 1. staging schema:
#    - stores raw data loaded from Excel/CSV files
#    - data here is not fully validated yet
#
# 2. production schema:
#    - stores clean reporting tables
#    - follows a star schema design for Power BI and analytics
#
# Star schema structure:
# - fact_financials is the central fact table
# - dim_department, dim_region, dim_category, and dim_date are dimension tables


import os

from dotenv import load_dotenv

from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    String,
    Float,
    Boolean,
    Date,
    BigInteger,
    UniqueConstraint,
    ForeignKey,
)

from sqlalchemy.orm import declarative_base, sessionmaker, relationship


# ---------------------------------------------------------------------------
# Load environment variables
# ---------------------------------------------------------------------------


load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "cfo_dashboard")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASSWORD", "password123")


# ---------------------------------------------------------------------------
# Build the PostgreSQL connection URL
# ---------------------------------------------------------------------------

DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"


# ---------------------------------------------------------------------------
# Create SQLAlchemy engine
# ---------------------------------------------------------------------------


engine = create_engine(
    DATABASE_URL,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True,
    echo=False,
)


# ---------------------------------------------------------------------------
# Create a session factory
# ---------------------------------------------------------------------------


Session = sessionmaker(bind=engine)


# ---------------------------------------------------------------------------
# Create separate Base classes
# ---------------------------------------------------------------------------
# SQLAlchemy models must inherit from a Base class.
#
# I am using two Base objects to keep staging models and production models
# logically separated in the code.
# ---------------------------------------------------------------------------

StagingBase = declarative_base()
ProductionBase = declarative_base()


# =============================================================================
# STAGING SCHEMA
# =============================================================================
# Staging tables store raw data as it arrives from the source files.
#
# Important:
# I do NOT add foreign keys in staging because raw data may contain invalid, missing, or inconsistent values.
#  Staging should accept the raw file first, then the transform layer will clean and validate it before loading production.
# =============================================================================


class RawTransaction(StagingBase):
    """
    Raw transaction-level data loaded from the source file.

    This table belongs to the staging schema because the records are still close
    to the original file format and have not yet been transformed into the final
    star schema.
    """

    __tablename__ = "raw_transactions"

    __table_args__ = (
        # Prevent loading the same transaction from the same source file twice.
        UniqueConstraint(
            "transaction_id",
            "source_file",
            name="uq_txn_source",
        ),
        {"schema": "staging"},
    )

    # Surrogate primary key generated by PostgreSQL.
    id = Column(BigInteger, primary_key=True, autoincrement=True)

    # Raw transaction fields from the source file.
    transaction_id = Column(String(20), nullable=False)
    date = Column(Date, nullable=False)
    year = Column(Integer, nullable=False)
    month = Column(Integer, nullable=False)
    department = Column(String(50), nullable=False)
    region = Column(String(50), nullable=False)
    category = Column(String(100), nullable=False)
    vendor = Column(String(100), nullable=False)
    amount = Column(Float, nullable=False)
    budget_amount = Column(Float, nullable=False)
    transaction_type = Column(String(20), nullable=False)
    is_anomaly = Column(Boolean, default=False)

    # Metadata columns added by the ETL pipeline.
    # These help track where the row came from and when it was loaded.
    source_file = Column(String(200), nullable=False)
    loaded_at = Column(String(30), nullable=False)


class RawMonthlySummary(StagingBase):
    """
    Raw monthly summary data loaded from the source file.

    This table keeps source-level monthly totals before the data is cleaned and
    prepared for final reporting.
    """

    __tablename__ = "raw_monthly_summary"

    __table_args__ = (
        # Prevent loading duplicate monthly summaries from the same file.
        UniqueConstraint(
            "year",
            "month",
            "department",
            "region",
            "source_file",
            name="uq_summary_source",
        ),
        {"schema": "staging"},
    )

    id = Column(BigInteger, primary_key=True, autoincrement=True)

    year = Column(Integer, nullable=False)
    month = Column(Integer, nullable=False)
    month_name = Column(String(20), nullable=False)
    quarter = Column(String(5), nullable=False)
    department = Column(String(50), nullable=False)
    region = Column(String(50), nullable=False)
    total_revenue = Column(Float, nullable=False)
    total_expense = Column(Float, nullable=False)
    total_budget = Column(Float, nullable=False)
    headcount = Column(Integer, nullable=False)

    source_file = Column(String(200), nullable=False)
    loaded_at = Column(String(30), nullable=False)


# =============================================================================
# PRODUCTION SCHEMA
# =============================================================================
# Production tables store the clean reporting model.


class DimDepartment(ProductionBase):
    """
    Department dimension table.

    One row represents one department.
    This avoids repeating department names in every transaction row.
    """

    __tablename__ = "dim_department"
    __table_args__ = {"schema": "production"}

    dept_key = Column(Integer, primary_key=True, autoincrement=True)
    dept_name = Column(String(50), nullable=False, unique=True)
    dept_head = Column(String(100), nullable=True)
    cost_centre = Column(String(20), nullable=True)

    # ORM relationship:
    # One department can be linked to many financial fact rows.
    #

    facts = relationship(
        "FactFinancials",
        back_populates="department",
        lazy="select",
    )


class DimRegion(ProductionBase):
    """
    Region dimension table.

    One row represents one business region.
    Region details can be used for geographic financial reporting.
    """

    __tablename__ = "dim_region"
    __table_args__ = {"schema": "production"}

    region_key = Column(Integer, primary_key=True, autoincrement=True)
    region_name = Column(String(50), nullable=False, unique=True)
    province = Column(String(50), nullable=True)
    country = Column(String(50), nullable=False, default="Canada")

    facts = relationship(
        "FactFinancials",
        back_populates="region",
        lazy="dynamic",
    )


class DimCategory(ProductionBase):
    """
    Financial category dimension table.

    One row represents one financial category, such as a revenue or expense type.
    """

    __tablename__ = "dim_category"
    __table_args__ = {"schema": "production"}

    category_key = Column(Integer, primary_key=True, autoincrement=True)
    category_name = Column(String(100), nullable=False, unique=True)
    category_group = Column(String(50), nullable=True)

    facts = relationship(
        "FactFinancials",
        back_populates="category",
        lazy="dynamic",
    )


class DimDate(ProductionBase):
    """
    Date dimension table.

    This table stores calendar attributes used for time-based analysis.
    A complete date table is important for Power BI time intelligence,
    such as month-over-month, year-over-year, and YTD reporting.
    """

    __tablename__ = "dim_date"
    __table_args__ = {"schema": "production"}

    # Example:
    # full_date = 2024-01-31
    # date_key  = 20240131
    date_key = Column(Integer, primary_key=True)

    full_date = Column(Date, nullable=False, unique=True)
    year = Column(Integer, nullable=False)
    quarter = Column(Integer, nullable=False)
    quarter_name = Column(String(5), nullable=False)
    month = Column(Integer, nullable=False)
    month_name = Column(String(20), nullable=False)
    week = Column(Integer, nullable=False)
    day_of_month = Column(Integer, nullable=False)

    # Python weekday convention:
    # Monday = 0
    # Sunday = 6
    day_of_week = Column(Integer, nullable=False)

    is_weekend = Column(Boolean, nullable=False)
    is_month_end = Column(Boolean, nullable=False)

    facts = relationship(
        "FactFinancials",
        back_populates="date",
        lazy="dynamic",
    )


class FactFinancials(ProductionBase):
    """
    Central financial fact table.

    One row represents one clean financial transaction.

    This table stores:
    - numeric metrics, such as amount and budget_amount
    - foreign keys that connect each transaction to dimensions

    Why use ForeignKey constraints in production?
    Production data should already be cleaned and validated.
    Foreign keys help make sure every fact row links to valid dimension records.

    Example:
    A fact row cannot use dept_key = 99 unless dept_key 99 exists in
    production.dim_department.
    """

    __tablename__ = "fact_financials"

    __table_args__ = (
        # Prevent duplicate transaction records in the production fact table.
        UniqueConstraint(
            "transaction_id",
            name="uq_fact_transaction",
        ),
        {"schema": "production"},
    )

    fact_key = Column(BigInteger, primary_key=True, autoincrement=True)

    # Original transaction ID from the source system/file.
    transaction_id = Column(String(20), nullable=False)

    # -----------------------------------------------------------------------
    # Foreign keys to dimension tables
    # -----------------------------------------------------------------------
    # These columns connect the fact table to the dimensions.
    #
    # ondelete='RESTRICT':
    # Prevents deleting a dimension row if fact rows still depend on it.
    # This protects reporting history from broken relationships.


    date_key = Column(
        Integer,
        ForeignKey("production.dim_date.date_key", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    dept_key = Column(
        Integer,
        ForeignKey("production.dim_department.dept_key", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    region_key = Column(
        Integer,
        ForeignKey("production.dim_region.region_key", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    category_key = Column(
        Integer,
        ForeignKey("production.dim_category.category_key", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Financial metrics.
    amount = Column(Float, nullable=False)
    budget_amount = Column(Float, nullable=False)

    # Transaction-level attributes.
    transaction_type = Column(String(20), nullable=False)
    is_anomaly = Column(Boolean, default=False)

    # Vendor is kept in the fact table because it is useful for anomaly checks.
   
    vendor = Column(String(100), nullable=True)

    # -----------------------------------------------------------------------
    # ORM relationships
    # -----------------------------------------------------------------------
    # These relationships let SQLAlchemy navigate from a fact row to its
    # related dimension records in Python.
    #

    date = relationship(
        "DimDate",
        back_populates="facts",
    )

    department = relationship(
        "DimDepartment",
        back_populates="facts",
    )

    region = relationship(
        "DimRegion",
        back_populates="facts",
    )

    category = relationship(
        "DimCategory",
        back_populates="facts",
    )


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================


def create_all_tables():
    """
    Create all staging and production tables in PostgreSQL.

    Creation order:
    1. Staging tables
       - No foreign key dependencies

    2. Production dimension tables
       - Created before fact table because the fact table references them

    3. Production fact table
       - Contains foreign keys to all dimensions

    SQLAlchemy uses the model relationships and foreign keys to create
    production tables in the correct dependency order.
    """

    StagingBase.metadata.create_all(
        engine,
        checkfirst=True,
    )

    ProductionBase.metadata.create_all(
        engine,
        checkfirst=True,
    )

    print("All staging and production tables created successfully.")


def test_connection():
    """
    Test whether Python can connect to PostgreSQL.

    This is useful before running ETL scripts because it confirms:
    - Docker container is running
    - PostgreSQL is accepting connections
    - .env credentials are correct
    """

    try:
        with engine.connect():
            print(f"Connected to PostgreSQL: {DB_NAME} @ {DB_HOST}:{DB_PORT}")

    except Exception as error:
        print(f"Connection failed: {error}")


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    test_connection()
    create_all_tables()